# Generated by Django 3.0.6 on 2020-05-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iitu_schedule_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='iitu_schedule_bot.TelegramChat'),
        ),
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='iitu_schedule_bot.TelegramUser'),
        ),
    ]
