# Generated by Django 3.0.5 on 2020-04-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0004_auto_20200414_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule3.Groups'),
        ),
    ]
