# Generated by Django 3.0.5 on 2020-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0005_auto_20200414_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
