# Generated by Django 3.0.5 on 2020-04-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0006_auto_20200414_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule3.TimeTable'),
        ),
    ]
