# Generated by Django 3.0.5 on 2020-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0007_event_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
