# Generated by Django 3.0.5 on 2020-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0009_event_room_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
