# Generated by Django 3.0.5 on 2020-04-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0010_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('0', 'Lecture'), ('1', 'Practice'), ('2', 'Laboratory')], max_length=20, null=True)),
                ('subject', models.ManyToManyField(to='schedule3.Subjects')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule3.Teacher')),
                ('time_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule3.TimeTable')),
            ],
        ),
    ]
