# Generated by Django 3.0.5 on 2020-04-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='subject',
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule3.Subjects'),
        ),
    ]
