# Generated by Django 3.0.5 on 2020-04-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0012_auto_20200416_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule3.Teacher'),
        ),
    ]
