# Generated by Django 3.0.5 on 2020-04-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0015_event_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bg_color',
        ),
    ]
