# Generated by Django 3.0.5 on 2020-04-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0018_auto_20200417_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='modal_page',
        ),
    ]
