# Generated by Django 3.0.5 on 2020-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0019_remove_event_modal_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.CharField(default='Waiting for everyone!', max_length=1000),
        ),
    ]
