# Generated by Django 3.0.5 on 2020-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule3', '0020_event_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='course',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
